# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=255, unique=True, verbose_name='IP')),
                ('host_style', models.SmallIntegerField(choices=[(0, '\u7269\u7406\u673a'), (1, '\u865a\u62df\u673a'), (2, '\u7f51\u7edc\u8bbe\u5907'), (3, '\u5176\u4ed6')])),
                ('sys_version', models.CharField(max_length=50, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58')),
                ('disk', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u786c\u76d8')),
                ('status', models.IntegerField(blank=True, choices=[(1, '\u672a\u4f7f\u7528'), (2, '\u5df2\u4f7f\u7528')], default=2, null=True, verbose_name='\u4f7f\u7528\u72b6\u6001')),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_useage', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory_useage', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u5b58')),
                ('disk_useage', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u786c\u76d8')),
                ('run_status', models.CharField(max_length=30, null=True, verbose_name='\u8fd0\u884c\u72b6\u6001')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hostid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assets', verbose_name='\u4e3b\u673aID')),
            ],
        ),
    ]
