# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.CharField(max_length=10, null=True, verbose_name='\u5b58\u6d3b\u72b6\u6001')),
                ('connections', models.CharField(max_length=30, null=True, verbose_name='\u8fde\u63a5\u4f7f\u7528\u7387')),
                ('qps_useage', models.CharField(max_length=10, null=True, verbose_name='\u67e5\u8be2\u541e\u5410\u91cf')),
                ('tps_useage', models.CharField(max_length=10, null=True, verbose_name='\u5199\u5165\u541e\u5410\u91cf')),
                ('slow_query', models.CharField(max_length=30, null=True, verbose_name='\u6162\u67e5\u8be2\u91cf')),
                ('buffer_useage', models.CharField(max_length=30, null=True, verbose_name='\u7f13\u5b58\u4f7f\u7528\u7387')),
                ('buffer_hitrate', models.CharField(max_length=30, null=True, verbose_name='\u7f13\u5b58\u547d\u4e2d\u7387')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='assets',
            name='host_style',
            field=models.SmallIntegerField(choices=[(1, '\u7269\u7406\u673a'), (2, '\u865a\u62df\u673a'), (3, '\u7f51\u7edc\u8bbe\u5907'), (4, '\u5176\u4ed6')]),
        ),
        migrations.AddField(
            model_name='mysqlinfo',
            name='hostid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assets', verbose_name='\u4e3b\u673aID'),
        ),
    ]
