# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-04 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180604_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlinfo',
            name='alive',
            field=models.IntegerField(blank=True, choices=[(1, '\u8fd0\u884c\u4e2d'), (2, '\u5df2\u505c\u6b62')], default=2, null=True, verbose_name='\u8fd0\u884c\u72b6\u6001'),
        ),
    ]
